export const foodTypes = [
  {
    id: "1",
    name: "Fruits",
    foodTypeUrl: "https://subzfresh.com/wp-content/uploads/2022/04/apple_158989157.jpg",
    foodItems: [
      "Apple",
      "Avocado",
      "Banana",
      "Berry",
      "Cherry",
      "Citrus",
      "Cranberry",
      "Fig",
      "Grape",
      "Kiwi",
      "Lemon",
      "Mango",
      "Melon",
      "Orange",
      "Papaya",
      "Pear",
      "Physalis",
      "Pineapple",
      "Pomegranate",
      "Prune",
      "Raspberry",
      "Roseberry",
      "Ruby Queen",
      "Strawberry",
      "Watermelon",
    ],
  },
  {
    id: "2",
    name: "Vegetables",
    foodTypeUrl: "https://cdn.britannica.com/17/196817-050-6A15DAC3/vegetables.jpg?w=400&h=300&c=crop",
    foodItems: [
      "Asparagus",
      "Beetroot",
      "Bell Pepper",
      "Broccoli",
      "Brussels",
      "Sprouts",
      "Cabbage",
      "Carrot",
      "Cauliflower",
      "Collard",
      "Corn",
      "Cucumber",
      "Eggplant",
      "Epazote",
      "Garlic",
      "Ginger",
      "Gourds",
      "Green Beans",
      "Horseradish",
      "Kohlrabi",
      "Leek",
      "Legumes",
      "Lima Bean",
      "Mushroom",
      "Mustard greens",
      "Okra",
      "Onion",
      "Parsley",
      "Parsnip",
      "Peas",
      "Potato",
      "Pumpkin",
      "Radish",
      "Rhubarb",
      "Rutabaga",
      "Spinach",
      "Sweet potato",
      "Taro",
      "Tomato",
      "Turnip",
      "Lentils",
      "Snap bean",
    ],
  },
  {
    id: "3",
    name: "Grains and Cereals",
    foodTypeUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Various_legumes.jpg/300px-Various_legumes.jpg",
    foodItems: [
      "Barley",
      "Bran",
      "Bread",
      "Breadfruit",
      "Cereal",
      "Corn",
      "Millet",
      "Oats",
      "Paddy Rice",
      "Pearl Millet",
      "Quinoa",
      "Rye",
      "Sorghum",
      "Wheat",
      "Wheat Bread",
    ],
  },
  {
    id: "4",
    name: "Legumes and Pulses",
    foodTypeUrl: "https://www.hsph.harvard.edu/nutritionsource/wp-content/uploads/sites/30/2019/10/shutterstock_716540269-1200x762.jpg",
    foodItems: [
      "Adzuki Bean",
      "Beans",
      "Lentils",
      "Mung Bean",
      "Kernels",
      "Peanuts",
      "Pinto Bean",
      "Soyabean",
    ],
  },
  {
    id: "5",
    name: "Nuts and Seeds",
    foodTypeUrl: "https://images.immediate.co.uk/production/volatile/sites/30/2021/02/almonds-9e25ce7.jpg?quality=90&webp=true&resize=600,545",
    foodItems: [
      "Almond",
      "Cashew",
      "Chestnut",
      "Hazelnut",
      "Kernels",
      "Peanut",
      "Pine Nuts",
      "Pistachio",
      "Walnut",
    ],
  },
  {
    id: "6",
    name: "Meat and Seafood",
    foodTypeUrl: "https://static.scientificamerican.com/sciam/cache/file/101091A0-11F7-4E40-ACD4FA284C65AFB6_source.jpg?w=590&h=800&06DB1FFA-92B0-4288-AD7814A0277DE724",
    foodItems: [
      "Bacon",
      "Beef",
      "Caviar",
      "Chicken",
      "Crab",
      "Crustacean Shellfish",
      "Fish",
      "Goat",
      "Lamb",
      "Mutton",
      "Oyster",
      "Pork",
      "Scallops",
      "Seafood",
      "Silkie",
      "Shrimp",
      "Shellfish",
      "Salmon",
      "Tuna",
    ],
  },
  {
    id: "7",
    name: "Dairy and Dairy Substitutes",
    foodTypeUrl: "https://domf5oio6qrcr.cloudfront.net/medialibrary/9685/iStock-544807136.jpg",
    foodItems: [
        "Butter",
        "Cheese",
        "Lard",
        "Margarine",
        "Mayonnaise",
        "Milk",
        "Yogurt"
    ],
  },
  {
    id: "8",
    name: "Oils and Condiments",
    foodTypeUrl: "https://www.greendna.in/cdn/shop/products/oliveoil2_1024x1024@2x.jpg?v=1627216046",
    foodItems: [
        "Olive Oil",
        "Peanut Butter",
        "Vinegar"
    ],
  },
  {
    id: "9",
    name: "Herbs and Spices",
    foodTypeUrl: "https://herbaria.plants.ox.ac.uk/bol/Content/Projects/plants400/images/Robinia_456.jpg",
    foodItems: [
        "Black Pepper",
        "Capsicum",
        "Chilli Pepper",
        "Cinnamon",
        "Clove",
        "Coriander",
        "Cumin",
        "Epazote",
        "Ginger",
        "Mustard",
        "Nutmeg",
        "Oregano",
        "Red Bell Pepper",
        "Saffron",
        "Vanilla Bean"
    ],
  },
  {
    id: "10",
    name: "Other Food Products",
    foodTypeUrl: "https://origin.club/media/catalog/product/cache/86eaafd287624d270d87c663dd3976d5/h/o/honey_2__1.jpg",
    foodItems: [
        "Honey",
        "Honeydrew",
        "Maple Syrup",
        "Sugar Cane",
    ],
  },
];
